import * as assert from 'node:assert';
import { getCoggitSystemPrompt } from '@coggit/core';

import { CLI_ENTRY_SENTENCE, CLI_STANDARD_ORIENTATION_SENTENCE, runInstructions } from './instructions';

function expectedComposite(kind: 'minimal' | 'standard'): string {
  const accessLines =
    kind === 'standard'
      ? [CLI_ENTRY_SENTENCE, CLI_STANDARD_ORIENTATION_SENTENCE]
      : [CLI_ENTRY_SENTENCE];
  return [...accessLines, getCoggitSystemPrompt(kind).content].join('\n');
}

suite('CLI instructions', () => {
  test('raw format prepends the entry sentence to the form content', () => {
    for (const kind of ['minimal', 'standard'] as const) {
      assert.strictEqual(runInstructions(kind, 'raw'), expectedComposite(kind));
    }
  });

  test('block format wraps the entry + content composite in managed markers', () => {
    for (const kind of ['minimal', 'standard'] as const) {
      const prompt = getCoggitSystemPrompt(kind);
      const lines = runInstructions(kind, 'block').split('\n');
      assert.strictEqual(lines[0], `<!-- coggit:begin system-prompt kind=${prompt.kind} version=${prompt.version} -->`);
      assert.strictEqual(lines[lines.length - 1], '<!-- coggit:end -->');
      assert.strictEqual(lines.slice(2, -1).join('\n'), expectedComposite(kind));
    }
  });

  test('the block management notice names the exact re-run command and the replace scope', () => {
    for (const kind of ['minimal', 'standard'] as const) {
      const notice = runInstructions(kind, 'block').split('\n')[1];
      assert.match(notice, /generated by `coggit instructions`/);
      assert.match(notice, new RegExp(`coggit instructions --kind ${kind} --format block`));
      assert.match(notice, /replace this whole block/);
    }
  });

  test('the entry sentence names the CLI entry and nothing more', () => {
    assert.match(CLI_ENTRY_SENTENCE, /`coggit` CLI/);
    assert.match(CLI_ENTRY_SENTENCE, /--help/);
    // The access layer teaches no command mechanics (restraint rule:
    // entry + stance only; --help self-describes).
    assert.doesNotMatch(CLI_ENTRY_SENTENCE, /snapshot|status|handbook|init/);
  });

  test('the orientation sentence rides the standard form only and names the answering commands', () => {
    assert.match(CLI_STANDARD_ORIENTATION_SENTENCE, /`coggit status`/);
    assert.match(CLI_STANDARD_ORIENTATION_SENTENCE, /`coggit status <path>`/);
    assert.match(runInstructions('standard', 'raw'), /coggit status/);
    // Minimal keeps entry-only access (owner ruling 2026-10-08).
    assert.doesNotMatch(runInstructions('minimal', 'raw'), /coggit status/);
  });
});
